/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/dramas/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Dramas */
    get: operations["list_dramas_api_dramas__get"];
    put?: never;
    /** Create Drama */
    post: operations["create_drama_api_dramas__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dramas/{drama_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Drama */
    get: operations["get_drama_api_dramas__drama_id__get"];
    /** Update Drama */
    put: operations["update_drama_api_dramas__drama_id__put"];
    post?: never;
    /** Delete Drama */
    delete: operations["delete_drama_api_dramas__drama_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/owner/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_owner_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/upload/poster": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Poster */
    post: operations["upload_poster_api_upload_poster_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_login_api_owner_login_post */
    Body_login_api_owner_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_upload_poster_api_upload_poster_post */
    Body_upload_poster_api_upload_poster_post: {
      /** File */
      file: string;
    };
    /**
     * DramaCountry
     * @enum {string}
     */
    DramaCountry: "Korea" | "China" | "Japan" | "Taiwan";
    /** DramaCreate */
    DramaCreate: {
      /** Title */
      title: string;
      /** Original Title */
      original_title?: string | null;
      /** Poster Path */
      poster_path?: string | null;
      /** Description */
      description: string;
      /** Review */
      review?: string | null;
      /** Rating */
      rating: number;
      status: components["schemas"]["DramaStatus"];
      /** Genres */
      genres?: components["schemas"]["DramaGenre"][];
      /** Year */
      year: number;
      /** Episodes Aired */
      episodes_aired?: number | null;
      /** Episodes Total */
      episodes_total?: number | null;
      country: components["schemas"]["DramaCountry"];
    };
    /**
     * DramaGenre
     * @enum {string}
     */
    DramaGenre:
      | "Romance"
      | "Comedy"
      | "Drama"
      | "Action"
      | "Thriller"
      | "Mystery"
      | "Fantasy"
      | "Historical"
      | "Xianxia"
      | "Melodrama"
      | "School"
      | "Office"
      | "Sports"
      | "Medical"
      | "Legal"
      | "Crime"
      | "Reality show"
      | "Supernatural"
      | "Military"
      | "Time travel"
      | "Reincarnation";
    /** DramaPublic */
    DramaPublic: {
      /** Title */
      title: string;
      /** Original Title */
      original_title?: string | null;
      /** Poster Path */
      poster_path?: string | null;
      /** Description */
      description: string;
      /** Review */
      review?: string | null;
      /** Rating */
      rating: number;
      status: components["schemas"]["DramaStatus"];
      /** Genres */
      genres?: components["schemas"]["DramaGenre"][];
      /** Year */
      year: number;
      /** Episodes Aired */
      episodes_aired?: number | null;
      /** Episodes Total */
      episodes_total?: number | null;
      country: components["schemas"]["DramaCountry"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * DramaStatus
     * @enum {string}
     */
    DramaStatus: "watching" | "completed" | "dropped" | "planned";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_dramas_api_dramas__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DramaPublic"][];
        };
      };
    };
  };
  create_drama_api_dramas__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DramaCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DramaPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_drama_api_dramas__drama_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        drama_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DramaPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_drama_api_dramas__drama_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        drama_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DramaCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DramaPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_drama_api_dramas__drama_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        drama_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_owner_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_owner_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_poster_api_upload_poster_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_poster_api_upload_poster_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
