"""create drama table

Revision ID: d7404435449b
Revises: 
Create Date: 2026-04-15 15:02:16.295554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7404435449b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drama',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'completed', 'dropped', 'planned', name='dramastatus'), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('episodes_aired', sa.Integer(), nullable=True),
    sa.Column('episodes_total', sa.Integer(), nullable=True),
    sa.Column('country', sa.Enum('korea', 'china', 'japan', 'taiwan', name='dramacountry'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drama')
    sa.Enum(name='dramastatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='dramacountry').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
